# Basic app information
name: rest_chooser
description: "A restaurant decision-making app that helps you choose where to eat when you (or your partner) can't decide. Features include random selection and head-to-head comparison modes."

# Prevents publishing to pub.dev (since this is a private app)
publish_to: 'none'

# Version format is MAJOR.MINOR.PATCH+BUILD_NUMBER
version: 1.0.0+1

# Dart SDK constraints
environment:
  sdk: ^3.7.2

# External packages the app depends on
dependencies:
  flutter:
    sdk: flutter
  # Used for persisting user preferences and restaurant data
  shared_preferences: ^2.1.0

  # iOS-style icons for the app
  cupertino_icons: ^1.0.8

# Dependencies only needed during development
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^5.0.0
  # Tools for generating app icons across platforms
  flutter_launcher_icons: ^0.14.3
  # Tool for creating native splash screens
  flutter_native_splash: ^2.3.13

# Flutter-specific configurations
flutter:
  # Enables use of Material Design widgets
  uses-material-design: true

  # Files to include in the app bundle
  assets:
    - assets/restaurants.json  # Restaurant data
    - assets/icon/            # App icon assets
    - assets/store_graphics/  # Store listing graphics

# Configuration for generating app icons
flutter_icons:
  android: true  # Generate Android icons
  ios: true      # Generate iOS icons
  image_path: "assets/icon/app_icon.png"  # Source image for icons
  adaptive_icon_background: "#40E0D0"     # Android adaptive icon background color
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"  # Android adaptive icon foreground
  # Generate icons for web and desktop platforms
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

# Configuration for splash screen appearance
flutter_native_splash:
  color: "#40E0D0"  # Main splash screen background color
  android_12:
    color: "#40E0D0"  # Android 12+ splash screen color
  ios: true   # Enable splash screen for iOS
  web: true   # Enable splash screen for web
